name: eslp
channels:
  - bioconda
  - conda-forge
dependencies:
  - biopython
  - cd-hit
  - imbalanced-learn
  - ipykernel
  - ipywidgets
  - matplotlib
  - numpy=2.2
  - pandas
  - scikit-learn
  - seaborn
  - shap
  - umap-learn
